language: c
sudo: required
dist: trusty
before_script:
- sudo add-apt-repository ppa:vala-team/ppa -y
- sudo apt-get update -qq
- sudo apt-get install -qq gnome-common libglib2.0-dev libgtk-3-dev
- sudo apt-get install -qq libsqlite3-dev libvala-0.30-dev valac-0.30 gobject-introspection
- sudo apt-get install -qq libwebkitgtk-3.0-dev libgee-dev 
- wget http://launchpadlibrarian.net/185318554/libparted-dev_3.2-6_amd64.deb
- dpkg -i libparted-dev_3.2-6_amd64.deb
- ./autogen.sh
- ./configure

script: make
