language: c
sudo: required
dist: precise
before_script:
- sudo add-apt-repository ppa:vala-team/ppa -y
- sudo add-apt-repository ppa:spvkgn/ppa -y
- sudo apt-get update -qq
- sudo apt-get install -qq gnome-common libglib2.0-dev libgtk-3-dev
<<<<<<< HEAD
- sudo apt-get install -qq libsqlite3-dev libvala-0.22-dev valac-0.22 gobject-introspection
- sudo apt-get install -qq libwebkitgtk-3.0-dev libparted-dev libgee-dev
- sudo apt-get install -qq libglibmm-2.4-1c2a libsigc++-2.0-0c2a
=======
- sudo apt-get install -qq libsqlite3-dev libvala-0.30-dev valac-0.30 gobject-introspection
- sudo apt-get install -qq libwebkitgtk-3.0-dev libgee-dev libparted-dev
>>>>>>> af18845e493164c87d999a4e69ca570354fba430
- ./autogen.sh
- ./configure

script: make

